apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp-qa/developer-charts
    targetRevision: HEAD
    path: spring-boot-pipeline
    helm:
      values: |
        domain: contract-first-idp-qa
        system: travelclick
        component: inventory-pipeline
  destination:
    server: https://kubernetes.default.svc
    namespace: travelclick-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
